[project]
name = "stock-forecasting-portfolio-optimisation"
version = "0.1.0"
description = ""

authors = [
    {name = "Mrciin",email = "chrostowskimarcin4@gmail.com"}
]
requires-python = ">=3.12"
dependencies = [
    "pandas (>=3.0.1,<4.0.0)",
    "datetime (>=6.0,<7.0)",
    "yfinance (>=1.2.0,<2.0.0)",
    "prophet (>=1.3.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false